### ISSUE TITLE
Error by the installation process of the node.js modules

### ISSUE THREAD

**Issue by f-wehrhausen** [plentymarkets/plentyDevTool#3]
**Operating System**: Windows 10
**plentyDevTool Version**:  1.4.2
**Node.Js Version**:  7.20.0

I was just about to pull the repo and install/run it locally. Unfortunately I didn't get very far. After cloning I wanted to install the necessary node.js modules. Unfortunately I fail from here, I get the following error message:

```
E:\plentyDevTool> npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: plentydevtool@1.4.2
npm ERR! Found: @angular/common@12.1.3
npm ERR! node_modules/@angular/common
npm ERR!   dev @angular/common@"12.1.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.0" from @ng-bootstrap/ng-bootstrap@9.1.3
npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!   @ng-bootstrap/ng-bootstrap@"^9.1.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\xxx\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Local\npm-cache\_logs\2021-12-09T19_36_50_858Z-debug.log
```

**Comment by FericelAnita** [comment]
> **Operating System**: Windows 10 **plentyDevTool Version**: 1.4.2 **Node.Js Version**: 7.20.0
> 
> I was just about to pull the repo and install/run it locally. Unfortunately I didn't get very far. After cloning I wanted to install the necessary node.js modules. Unfortunately I fail from here, I get the following error message:
> 
> ```
> E:\plentyDevTool> npm i
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: plentydevtool@1.4.2
> npm ERR! Found: @angular/common@12.1.3
> npm ERR! node_modules/@angular/common
> npm ERR!   dev @angular/common@"12.1.3" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/common@"^11.0.0" from @ng-bootstrap/ng-bootstrap@9.1.3
> npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
> npm ERR!   @ng-bootstrap/ng-bootstrap@"^9.1.3" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\xxx\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\xxx\AppData\Local\npm-cache\_logs\2021-12-09T19_36_50_858Z-debug.log
> ```

Hi,
This issue is probably related to the incompatibility between Angular 12 and Node 15/16 (npm 7).

You can downgrade your node version to Node 14 (npm 6) or run `npm install --legacy-peer-deps`. 
"The --legacy-peer-deps flag was introduced with v7 as a way to bypass peerDependency auto-installation; it tells NPM to ignore peer deps and proceed with the installation anyway. This is how things used to be with NPM v4 thru v6."

Let us know if it works.
